import NavBarSession from "./Navs/NavBarSession";
import Bar from "./Bar/Bar";
import Footer from "./Footer";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { useSelector } from "react-redux";
import axios from "axios";
import { useState } from "react";

const CardBuy = (props) => {
  const { listBuy: product_buy } = useSelector((state) => state.product_buy);

  const router = useRouter();
  const [orderState, setOrderState] = useState(false);
  const [buy, setBuy] = useState({
    value: product_buy,
  });

  const buyNow = async () => {
    const response = await axios.post("/api/buy", buy);
    if ((response.data.message = "your order has completed sucessfully")) {
      setOrderState(true);
    }
  };

  const Return = () => {
    if (!orderState) {
      return (
        <div className="border-gray-300 w-10/12 h-[30rem] border-2 my-5 flex justify-center flex-col">
          <div className="flex flex-col h-4/6 md:flex-row">
            <div className="w-40 h-40 border-2 border-violet-700 m-auto md:w-60 md:h-60">
              <Image
                alt="product"
                src="/img/product/product1.jpg"
                width="300px"
                height="300px"
                className=""
              ></Image>
            </div>
            <div className="m-auto md:flex md:flex-col text-center">
              <p className="text-lg text-cyan-700">{props.productTitle}</p>
              <p className="md:text-sm md:w-80 w-60 text-xs">
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor,
                delectus. Magnam amet accusamus tempora illum placeat cum sed
                reiciendis, est, tempore tenetur facere voluptatum debitis
                temporibus voluptatibus molestiae, magni odit.
              </p>
            </div>
          </div>
          <div className="flex flex-col h-2/6 md:flex-row">
            <button
              className="m-auto w-4/6 h-14 bg-green-500 text-xl text-white md:w-5/12"
              onClick={() => buyNow()}
            >
              BUY
            </button>
            <button
              className="m-auto w-4/6 h-14 bg-red-500 text-xl text-white md:w-5/12"
              onClick={() => router.push("/")}
            >
              CANCEL
            </button>
          </div>
        </div>
      );
    } else {
      return (
        <>
          <div className="border-gray-300 w-10/12 h-[30rem] text-center border-2 my-5 flex justify-center flex-col">
            <span className="text-green-500 text-4xl" onClick={() => router.push('/')}>
              Your order has created sucessfully
            </span>
          </div>
        </>
      );
    }
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBarSession />

        <Bar></Bar>

        <div className="flex justify-center">{Return()}</div>

        <Footer />
      </main>
    </div>
  );
};

export default CardBuy;
