import Head from 'next/head'
import Footer from '../components/Footer'
import NavBar from '../components/Navs/NavBar'
import Bar from '../components/Bar'

function Blog() {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <NavBar />
                <Bar />

                <div className="w-full h-full bg-gray-100">
                    <div className="m-8 border-xlv border-gray-100 shadow-2xl flex flex-col justify-center bg-white">
                        <h2 className="text-4xl mx-8 text-violet-700">Lorem ipsum</h2>
                        <div>
                            <p className="text-xs m-6 text-gray-600">Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam facere vel cum voluptates officia, sint eum perspiciatis vitae tenetur incidunt. Aperiam rem sint nostrum quo dolor necessitatibus tenetur voluptates pariatur?
                                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nesciunt fugiat totam tempore voluptates quos, distinctio voluptas id doloribus soluta, labore, enim reprehenderit nisi magnam unde quae ab animi vitae veritatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum natus aperiam iste nam praesentium consequuntur dolorem dignissimos neque veritatis facere. Inventore dolor iste voluptatum! Soluta aliquam eos ducimus odit vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam temporibus consequatur, ratione expedita et veniam soluta maxime provident quaerat cupiditate neque voluptatum vero? Corporis nisi debitis in culpa, molestiae aut! Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus ab consectetur voluptatem eaque pariatur, hic velit incidunt blanditiis, obcaecati consequatur, a corporis aspernatur et. Temporibus dignissimos doloribus vero fuga. Natus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus accusantium est corporis, ex animi aliquam repudiandae velit amet perspiciatis, quos voluptatem blanditiis porro cupiditate ad. Voluptatum doloribus dolorum repudiandae quae?
                            </p>

                            <p className="text-xs m-6 text-gray-600">Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam facere vel cum voluptates officia, sint eum perspiciatis vitae tenetur incidunt. Aperiam rem sint nostrum quo dolor necessitatibus tenetur voluptates pariatur?
                                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nesciunt fugiat totam tempore voluptates quos, distinctio voluptas id doloribus soluta, labore, enim reprehenderit nisi magnam unde quae ab animi vitae veritatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum natus aperiam iste nam praesentium consequuntur dolorem dignissimos neque veritatis facere. Inventore dolor iste voluptatum! Soluta aliquam eos ducimus odit vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam temporibus consequatur, ratione expedita et veniam soluta maxime provident quaerat cupiditate neque voluptatum vero? Corporis nisi debitis in culpa, molestiae aut! Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus ab consectetur voluptatem eaque pariatur, hic velit incidunt blanditiis, obcaecati consequatur, a corporis aspernatur et. Temporibus dignissimos doloribus vero fuga. Natus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus accusantium est corporis, ex animi aliquam repudiandae velit amet perspiciatis, quos voluptatem blanditiis porro cupiditate ad. Voluptatum doloribus dolorum repudiandae quae?
                            </p>

                            <p className="text-xs m-6 text-gray-600">Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam facere vel cum voluptates officia, sint eum perspiciatis vitae tenetur incidunt. Aperiam rem sint nostrum quo dolor necessitatibus tenetur voluptates pariatur?
                                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nesciunt fugiat totam tempore voluptates quos, distinctio voluptas id doloribus soluta, labore, enim reprehenderit nisi magnam unde quae ab animi vitae veritatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum natus aperiam iste nam praesentium consequuntur dolorem dignissimos neque veritatis facere. Inventore dolor iste voluptatum! Soluta aliquam eos ducimus odit vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam temporibus consequatur, ratione expedita et veniam soluta maxime provident quaerat cupiditate neque voluptatum vero? Corporis nisi debitis in culpa, molestiae aut! Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus ab consectetur voluptatem eaque pariatur, hic velit incidunt blanditiis, obcaecati consequatur, a corporis aspernatur et. Temporibus dignissimos doloribus vero fuga. Natus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus accusantium est corporis, ex animi aliquam repudiandae velit amet perspiciatis, quos voluptatem blanditiis porro cupiditate ad. Voluptatum doloribus dolorum repudiandae quae?
                            </p>

                            <p className="text-xs m-6 text-gray-600">Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam facere vel cum voluptates officia, sint eum perspiciatis vitae tenetur incidunt. Aperiam rem sint nostrum quo dolor necessitatibus tenetur voluptates pariatur?
                                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nesciunt fugiat totam tempore voluptates quos, distinctio voluptas id doloribus soluta, labore, enim reprehenderit nisi magnam unde quae ab animi vitae veritatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum natus aperiam iste nam praesentium consequuntur dolorem dignissimos neque veritatis facere. Inventore dolor iste voluptatum! Soluta aliquam eos ducimus odit vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam temporibus consequatur, ratione expedita et veniam soluta maxime provident quaerat cupiditate neque voluptatum vero? Corporis nisi debitis in culpa, molestiae aut! Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus ab consectetur voluptatem eaque pariatur, hic velit incidunt blanditiis, obcaecati consequatur, a corporis aspernatur et. Temporibus dignissimos doloribus vero fuga. Natus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus accusantium est corporis, ex animi aliquam repudiandae velit amet perspiciatis, quos voluptatem blanditiis porro cupiditate ad. Voluptatum doloribus dolorum repudiandae quae?
                            </p>

                            <p className="text-xs m-6 text-gray-600">Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam facere vel cum voluptates officia, sint eum perspiciatis vitae tenetur incidunt. Aperiam rem sint nostrum quo dolor necessitatibus tenetur voluptates pariatur?
                                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nesciunt fugiat totam tempore voluptates quos, distinctio voluptas id doloribus soluta, labore, enim reprehenderit nisi magnam unde quae ab animi vitae veritatis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum natus aperiam iste nam praesentium consequuntur dolorem dignissimos neque veritatis facere. Inventore dolor iste voluptatum! Soluta aliquam eos ducimus odit vel. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam temporibus consequatur, ratione expedita et veniam soluta maxime provident quaerat cupiditate neque voluptatum vero? Corporis nisi debitis in culpa, molestiae aut! Lorem ipsum dolor sit amet consectetur adipisicing elit. Temporibus ab consectetur voluptatem eaque pariatur, hic velit incidunt blanditiis, obcaecati consequatur, a corporis aspernatur et. Temporibus dignissimos doloribus vero fuga. Natus? Lorem ipsum dolor sit amet consectetur adipisicing elit. Minus accusantium est corporis, ex animi aliquam repudiandae velit amet perspiciatis, quos voluptatem blanditiis porro cupiditate ad. Voluptatum doloribus dolorum repudiandae quae?
                            </p>
                        </div>
                    </div>
                </div>

            </main>

            <Footer />
        </div>
    )
}

export default Blog