import Head from 'next/head'
import Footer from '../components/Footer'
import Bar from '../components/Bar'
import NavBar from '../components/Navs/NavBar'
import NavBarSession from '../components/Navs/NavBarSession'
import { useState } from 'react'
import { useEffect } from 'react'
import axios from 'axios'

export default function Home() {
  const [Session, setSession] = useState({})

  useEffect(() => {
    async function fetchData() {
      const response = await axios.get("/api/auth/loginIndex");
      setSession(response.data);
    }
    fetchData()
  }, [])
  

  if(Session.status === false) {
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main>
  
          <NavBar />
  
          <Bar>
            <div className="w-full bg-no-repeat back bg-cover md:h-[40vw] h-[2vw] md:flex items-center justify-center">
              <div className="bg-cyan-500 hidden md:h-[30vw] md:w-[70vw] md:flex justify-center items-center rounded-xl">
                <p className="text-white text-8xl">Get Out</p>
              </div>
            </div>
          </Bar>
  
  
  
          <Footer />
        </main>
  
  
      </div>
    )
  } else if (Session.status === true) {
      return (
        <div>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <main>
    
            <NavBarSession />
    
            <Bar>
              <div className="w-full bg-no-repeat back bg-cover md:h-[40vw] h-[2vw] md:flex items-center justify-center">
                <div className="bg-cyan-500 hidden md:h-[30vw] md:w-[70vw] md:flex justify-center items-center rounded-xl">
                  <p className="text-white text-8xl">Get Out</p>
                </div>
              </div>
            </Bar>
    
    
    
            <Footer />
          </main>
    
    
        </div>
      )
  } else {
    return (
      <h1>Hagale</h1>
    )
  }
  
}
