import Head from 'next/head'
import Footer from '../components/Footer'
import NavBar from '../components/Navs/NavBar'
import Bar from '../components/Bar'
import Image from 'next/image'

function Products() {

    let cards = []
    for (let i = 1; i <= 12; i++) {
      cards.push(
        <div className="w-44 md:w-56 flex md:mx-10 flex-col justify-center border-2 border-violet-700 text-center my-5 mx-1 md:items-center" key={i}>
          <div className="md:hidden">
            <Image src="/img/product/product1.jpg" alt='product' width="172px" height="112px" />
          </div>
          <div className="hidden md:block">
            <Image src="/img/product/product1.jpg" alt='product' width="220px" height="200px" />
          </div>
          <p className="text-violet-700 mt-1">Product title</p>
          <div className="flex items-center justify-between">
            <div className="container w-16 h-3 flex ml-1 mr-auto">
              <div>
                <Image src="/img/product/start.png" alt="start" width="100%" height="100%" />
              </div>
              <div>
                <Image src="/img/product/start.png" alt="start" width="100%" height="100%" />
              </div>
              <div>
                <Image src="/img/product/start.png" alt="start" width="100%" height="100%" />
              </div>
              <div>
                <Image src="/img/product/start.png" alt="start" width="100%" height="100%" />
              </div>
              <div>
                <Image src="/img/product/start.png" alt="start" width="100%" height="100%" />
              </div>
            </div>
            <div className="md:ml-24">
              <span className="mr-1 text-green-500">$3</span>
            </div>
          </div>
          <div className="flex flex-col md:w-5/6 w-full text-center md:mb-4">
            <a href="#" className="bg-white border-violet-700 border-2 px-7 py-0 rounded-lg text-violet-700 mt-2">ADD TO CAR</a>
            <a href="#" className="bg-violet-700 px-7 md:px-0 py-0 rounded border-2 border-violet-700 text-white mt-2">BUY NOW</a>
          </div>
        </div>
      )
    }
  
  
    return (
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main>
          <NavBar />
  
          <Bar />
  
          <div className="flex flex-col text-center">
            <h2 className="text-4xl text-violet-700 md:my-10">The Best e-Commerce</h2>
            <div className="flex flex-wrap justify-center md:mb-20 md:mt-10">
  
              {
                cards
              }
  
            </div>
          </div>
  
  
          <Footer />
        </main>
      </div>
    );
  }

export default Products