import Image from "next/image";
import Head from "next/head";
import favicon from "../public/favicon.ico";
import { useRouter } from "next/router";
import { useState, useEffect } from "react";
import axios from "axios";

const Register = () => {
  const router = useRouter();
  const [session, setSession] = useState(undefined);
  const [register, setRegister] = useState({
    username: "",
    email: "",
    password: "",
  });

  const handleChange = (e) => {
    setRegister({
      ...register,
      [e.target.name]: e.target.value,
    });
  };

  useEffect(() => {
    async function fetchData() {
      const response = await axios.get("/api/revition");
      setSession(response.data.status);
    }
    fetchData();
  }, []);

  const handleSubmit = async (e) => {
    try {
      e.preventDefault();
      const response = await axios.post("/api/auth/user", register);
      console.log(response);
      router.push("/Signin");
    } catch (error) {
      console.log(error);
    }
  };
  if (session === false) {
    return (
      <>
        <Head>
          <title>Register</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="shortcut icon" href={favicon.src} type="image/x-icon" />
        </Head>
        <div className="w-screen h-screen bg-gradient-to-r from-indigo-500/50 via-purple-500/50 to-pink-500/50 flex flex-col items-center justify-center">
          <div className="bg-gray-100/75 w-11/12 rounded-3xl sm:h-3/6 h-[28rem] flex flex-col items-center sm:w-4/12">
            <div className="w-24 py-5 flex pr-5 pl-4 bg-blue-900 rounded-full mt-10">
              <Image alt="user icon" src="/c.png" width="64" height="64px" />
            </div>
            <div>
              <form>
                <div className="flex my-8">
                  <div className="bg-blue-900 w-10 px-3 pb-1 pt-3">
                    <Image
                      alt="icon user"
                      width="64px"
                      height="64px"
                      src="/img/login/user_little.png"
                    />
                  </div>
                  <input
                    type="text"
                    name="username"
                    placeholder="User Name"
                    onChange={handleChange}
                    className="bg-[#395173] text-zinc-100 pl-3 py-2 focus:outline-none caret-zinc-400"
                  />
                </div>
                <div className="flex my-8">
                  <div className="bg-blue-900 w-10 px-3 pb-1 pt-3">
                    <Image
                      alt="icon user"
                      width="64px"
                      height="64px"
                      src="/img/login/email.png"
                    />
                  </div>
                  <input
                    type="email"
                    name="email"
                    placeholder="Email ID"
                    onChange={handleChange}
                    className="bg-[#395173] text-zinc-100 pl-3 py-2 focus:outline-none caret-zinc-400"
                  />
                </div>
                <div className="flex my-8">
                  <div className="bg-blue-900 w-10 px-3 py-2">
                    <Image
                      alt="icon user"
                      width="64px"
                      height="64px"
                      src="/img/login/lock.png"
                    />
                  </div>
                  <input
                    type="password"
                    name="password"
                    placeholder="Password"
                    onChange={handleChange}
                    className="bg-[#395173] text-zinc-100 pl-3 py-2 focus:outline-none caret-zinc-400"
                  />
                </div>
              </form>
            </div>
            <div className="flex flex-col items-center">
              <div className="flex mb-10">
                <div className="mr-3">
                  <label className="text-[#395173]">
                    <input
                      type="checkbox"
                      className="h-4 w-4 border-2 accent-blue-900 border-blue-500"
                    />{" "}
                    Remember me
                  </label>
                </div>
              </div>
            </div>
          </div>
          <button
            className="bg-gradient-to-t from-gray-100 text-white w-4/6 py-3 text-2xl font-extrabold rounded-b-2xl sm:w-1/6"
            onClick={handleSubmit}
          >
            Sign Up
          </button>
        </div>
      </>
    );
  } else if (session === true) {
    router.push("/");
  } else {
    return (
      <>
        <div className="h-screen my-0 w-full flex items-center justify-center bg-cyan-700 sm:my-1 sm:h-screen">
          <p className="text-4xl text-violet-300 font-extrabold">Loading... </p>
        </div>
      </>
    );
  }
};

export default Register;
